### ISSUE TITLE
When fsync is slow race condition can occur

### ISSUE THREAD

**Issue by phiresky** [larkery/zsh-histdb#65]
I'm currently running a very disk intense task, which means that `sync` on my root disk takes around 2 - 3 seconds.

This means that the histdb insertion and update also takes that amount of time since a `sqlite3` command always syncs to disk when it exits. I tried experimenting with options like `pragma synchronous=off` but I guess when an sqlite process exits it will force fsync regardless of those settings.

Every time I run a command in this state, the UPDATE query it will always fail after a few seconds with `database is locked`, because the INSERT has not yet completed.

I managed to solve this by making histdb run all sqlite commands that do not have output in the same sqlite3 connection and keeping it open: https://github.com/phiresky/zsh-histdb/commit/6b836ea475121bd4b24372de364c674c97bde5e7

This approach has two problems that might need to be fixed for this to be merged back:

1. Uses coproc which I've never seen anywhere. Should be replacable with just starting the process and redirecting stdin from a named pipe...
2. Can't exit shell with ctrl+d (`zsh: you have running jobs.`)

I guess this is a regression caused by #51.

**Comment by phiresky** [comment]
Found a better solution just using a named pipe: https://github.com/larkery/zsh-histdb/compare/master...phiresky:master

I'll keep using that for a while to see if it has problems.

**Comment by larkery** [comment]
This is a good idea which I like a lot, thank you. If it doesn't have any nightmare side-effects, and I can't forsee any right now it would be a good one to put in.

The only potential issue I can imagine is whether there's any way to get multiple concurrent writes on the pipe. This would be getting into details of shell that are beyond me. I guess the shell is generally single-threaded, having only process-level parallelism, but I don't know whether can ever `fork`, inherit the fd for the pipe, and then tread on its own toes.

**Comment by phiresky** [comment]
just as an update: i've been using this for a while now and it's been working great, haven't noticed any regressions.

> whether there's any way to get multiple concurrent writes on the pipe

I don't really know of any way that could happen unintentionally. Subshells might be an issue, but running

```zsh
( echo foo; echo bar )
```

creates a history entry for `( echo foo; echo bar )`, not one for `echo foo` and one for `echo bar`.


You can probably intentionally cause problems by doing `( echo hi >&$HISTDB_FD )` which I guess causes a write to the sqlite pipe from the subshell which is in a different process.

**Comment by larkery** [comment]
I guess that subshells run in noninteractive mode which doesn't do history append, so creating an unsafe outcome this way would require special effort. If you have had this running in typical use for some time then it seems likely that it doesn't have any bad faults in it, so I have merged it onto master.

Thanks for your work on this.

**Comment by phiresky** [comment]
There might be a problem: If you do

```
( sleep 1h ) & disown
ctrl+d
```

the shell does not quit with the changes but it does with a clean zsh (`zsh -d -f`)

needs more investigation though

**Comment by larkery** [comment]
What's the symptom? If I do `( sleep 1m ) & disown ^D` I get that appended to my log...

**Comment by phiresky** [comment]
It gets added correctly to the db, but the shell just stays open for me if i do that, when it should close. Maybe because the sqlite fifo file descriptor stays open when there's a subprocess started?

**Comment by phiresky** [comment]
Ok nevermind I guess that hanging I'm seeing is caused by a different part of my zshrc, still happens when I disable histdb.

**Comment by larkery** [comment]
OK - good luck tracking it down!

**Comment by phiresky** [comment]
one more thing that might be a good idea (found while tracking down the unrelated issue):

```diff
diff --git a/sqlite-history.zsh b/sqlite-history.zsh
index ab1f518..5c0d23f 100644
--- a/sqlite-history.zsh
+++ b/sqlite-history.zsh
@@ -1,5 +1,8 @@
 which sqlite3 >/dev/null 2>&1 || return;
 
+
+zmodload zsh/system # for sysopen
+
 typeset -g HISTDB_QUERY=""
 if [[ -z ${HISTDB_FILE} ]]; then
     typeset -g HISTDB_FILE="${HOME}/.histdb/zsh-history.db"
@@ -25,7 +28,8 @@ _histdb_start_sqlite_pipe () {
     local PIPE=$(mktemp -u)
     setopt local_options no_notify no_monitor
     mkfifo $PIPE
-    exec {HISTDB_FD}<>$PIPE
+    #exec {HISTDB_FD}<>$PIPE
+    sysopen -rw -o cloexec -u HISTDB_FD -- $PIPE
     rm $PIPE
     sqlite3 -batch "${HISTDB_FILE}" <&$HISTDB_FD >/dev/null &|
     zshexit() { exec {HISTDB_FD}>&-; } # https://stackoverflow.com/a/22794374/2639190
```

currently the histdb fd is inherited by some(?) processes started from the shell. if pipe is opened with CLOEXEC that doesn't happen.

**Comment by larkery** [comment]
That seems sensible - I remember reading in the sqlite bug analysis logs that accidental writes to a leaked fd are a common cause of database corruption in badly written programs, so we should make that impossible. Will amend.

**Comment by larkery** [comment]
By the way, thanks for your work on this, I appreciate it.
